import asyncio
import logging
from src.core.database import db
from src.core.websocket import manager  # Matches your main.py import

logger = logging.getLogger(__name__)


async def generate_course_content_task(course_id: str, user_id: str, topic_prompt: str):
    """
    Background task that generates course content and notifies the user via WebSocket.
    """
    try:
        # 1. Notify: Started
        await manager.send_to_user(
            user_id,
            {
                "type": "COURSE_UPDATE",
                "courseId": course_id,
                "status": "started",
                "message": "AI is thinking...",
            },
        )

        # -------------------------------------------------------------
        # SIMULATION: Replace this sleep with your actual OpenAI call
        # -------------------------------------------------------------
        await asyncio.sleep(3)

        # 2. Notify: Processing
        await manager.send_to_user(
            user_id,
            {
                "type": "COURSE_UPDATE",
                "courseId": course_id,
                "status": "processing",
                "message": "Structuring modules...",
            },
        )

        # Mock Data (This is where the AI response structure goes)
        generated_modules = [
            {
                "title": "Module 1: Introduction",
                "topics": [
                    {"title": f"What is {topic_prompt}?", "content": "Intro content..."},
                    {"title": "History & Context", "content": "Historical context..."},
                ],
            },
            {
                "title": "Module 2: Core Concepts",
                "topics": [{"title": "Key Principles", "content": "Deep dive content..."}],
            },
        ]

        # 3. Save to Database
        for i, mod_data in enumerate(generated_modules):
            # Create Module
            new_module = await db.module.create(
                data={
                    "courseId": course_id,
                    "title": mod_data["title"],
                    "order": i,
                    "description": "AI Generated Module",
                }
            )

            # Create Topics for this Module
            for j, top_data in enumerate(mod_data["topics"]):
                await db.topic.create(
                    data={
                        "moduleId": new_module.id,
                        "title": top_data["title"],
                        "content": top_data["content"],
                        "order": j,
                        "estimatedHours": 0.5,
                    }
                )

        # 4. Finalize Course Status
        await db.course.update(
            where={"id": course_id},
            data={
                "isAIGenerated": True,
                "description": f"A comprehensive course on {topic_prompt} generated by AI.",
            },
        )

        # 5. Notify: Success
        logger.info(f"AI Generation Complete for {course_id}")
        await manager.send_to_user(
            user_id,
            {
                "type": "COURSE_READY",
                "courseId": course_id,
                "status": "completed",
                "message": "Your course is ready!",
            },
        )

    except Exception as e:
        logger.error(f"AI Generation Failed: {e}")
        await manager.send_to_user(
            user_id,
            {
                "type": "COURSE_ERROR",
                "courseId": course_id,
                "message": "Failed to generate course.",
            },
        )
